In [1]:
print('hello world')

hello world


### Numpy

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with collection of mathematical functions to operate on these data structures.

In [2]:
# pip install numpy

In [ ]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
## 1d-array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2d-array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
print(np.arange(0,10,2))
print(np.arange(0,10,2).reshape(5,1))

[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) 
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size)  
print("Data type:", arr.dtype)  
print("Item size (in bytes):", arr.itemsize) 


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [10]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])


print("Addition:", arr1+arr2)

print("Substraction:", arr1-arr2)

print("Multiplication:", arr1 * arr2)

print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
## Universal Function
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


### slicing and indexing

In [12]:

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [13]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [14]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [15]:
## Modifying array elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


### statistical concepts--Normalization
#### To have a mean of 0 and standard deviation of 1

In [17]:


data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [18]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print("Mean:", mean)


median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [19]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data>=5])
print(data[(data>=5) & (data<=8)])

[ 5  6  7  8  9 10]
[5 6 7 8]


In [29]:
### random
print(np.random.rand(1,100))
print(np.random.rand(3))
# np.random.randint(30,40)
print(np.random.randint(29,99,3))
np.random.randint(50,100,(4,5))
# np.random.randint(3,99,(4,3,3))

[[0.84371427 0.12013318 0.59206082 0.07757847 0.65316988 0.99529837
  0.45676733 0.78485057 0.96190698 0.8444375  0.03396492 0.49368693
  0.76852263 0.88753223 0.28420749 0.20266314 0.55163846 0.2389061
  0.40253875 0.8633592  0.55776079 0.85590106 0.97516784 0.15194378
  0.47063326 0.81926735 0.81882189 0.33855552 0.72025849 0.62920295
  0.56368503 0.60062448 0.66775918 0.30198006 0.61484482 0.86538732
  0.96246874 0.44279935 0.68831126 0.26456186 0.3222949  0.48206534
  0.49813422 0.88273173 0.99644842 0.54460075 0.77843511 0.22009145
  0.97607224 0.83745522 0.32139993 0.83806302 0.68143674 0.20548079
  0.53830558 0.02925157 0.90757703 0.4452275  0.53467133 0.63215684
  0.98687325 0.34932406 0.14211181 0.32237633 0.29751615 0.2982578
  0.39641944 0.12410408 0.55532552 0.56263549 0.35521769 0.69108728
  0.05879641 0.03214621 0.4825412  0.79975953 0.16687799 0.52901329
  0.10137707 0.27602273 0.94976469 0.9042805  0.29123496 0.54494601
  0.40798245 0.1049752  0.72126802 0.42595966 0.14

array([[91, 89, 93, 69, 92],
       [81, 68, 61, 76, 75],
       [77, 70, 77, 93, 63],
       [95, 61, 51, 93, 56]])

In [20]:
### numpy methods
arr1 = np.random.randint(40,99,10)
arr1
print(f'the max value of array is {arr1.max()}')
print(f'the min value of array is {arr1.min()}')

print(arr1.argmax())
print(arr1.argmin())

the max value of array is 98
the min value of array is 44
4
2


In [21]:
### indexing and slicing
import numpy as np
arr1 = np.arange(20,50,2)
arr1
arrindexing = arr1[2:12]
print(arrindexing)
negativeindexing = arr1[-13:-3]
print(negativeindexing)
# arr1[-13:-4:2]
# arr1[-5:-14:-2]
# arr1[10:]
print(arr1[:])
print(arr1[::-1])

[24 26 28 30 32 34 36 38 40 42]
[24 26 28 30 32 34 36 38 40 42]
[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20]
